---
- name: chkrootkit | set config file path for modern Debian-based distros
  set_fact:
    chkrootkit_conf: "/etc/chkrootkit/chkrootkit.conf"
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22) or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 12)

- name: chkrootkit | set config file path for old Debian-based distros
  set_fact:
    chkrootkit_conf: "/etc/chkrootkit.conf"
  when: not ((ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22) or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 12))

- name: chkrootkit | install tool from repo
  package:
    name: chkrootkit
    state: present
    update_cache: true

- name: chkrootkit | enable daily scheduled runs
  lineinfile:
    dest: "{{ chkrootkit_conf }}"
    regexp: "^RUN_DAILY="
    line: "RUN_DAILY=\"true\""
    state: present

- name: chkrootkit | setup receiver email address for reports
  lineinfile:
    dest: "{{ chkrootkit_conf }}"
    line: "REPORT_EMAIL=\"{{ antirootkits_mail_to }}\""
    state: present

- name: chkrootkit | install logrotate config
  template:
    src: chkrootkit.logrotate
    dest: /etc/logrotate.d/chkrootkit
    owner: root
    group: root
    mode: 0644

- name: chkrootkit | install cron job
  template:
    src: chkrootkit.cron.j2
    dest: /etc/cron.daily/chkrootkit
    owner: root
    group: root
    mode: 0755
