---

- name: Shell Detector | install prerequisites
  package:
    name:
    - git
    state: present
    update_cache: yes

- name: Shell Detector | install tool
  git:
    repo: https://github.com/emposha/Shell-Detector.git
    dest: "{{ shelldetector_install_directory }}"
    clone: yes
    force: yes
    depth: 1

- name: Shell Detector | create log directory
  file:
    path: "{{ shelldetector_log_directory }}"
    mode: 0750
    owner: root
    group: root
    state: directory

- name: Shell Detector | install cron script
  template:
    src: shelldetector.cron.j2
    dest: "/usr/local/bin/shelldetector_cron.sh"
    owner: root
    group: root
    mode: 0750

- name: Shell Detector | creates daily cronjob
  cron:
    name: "Launch Shell Detector audit"
    hour: "{{ shelldetector_cron_hour }}"
    minute: "{{ shelldetector_cron_minute }}"
    weekday: "*"
    cron_file: "shelldetector"
    user: "root"
    job: "/usr/local/bin/shelldetector_cron.sh 2>&1 | logger"
