---

- name: Shell Detector | install tool
  get_url:
    dest: /usr/local/bin/
    url: https://raw.github.com/emposha/Shell-Detector/master/shelldetect.py
    owner: root
    group: root
    mode: 0750

- name: Shell Detector | create log directory
  file:
    path: /var/log/shelldetector
    mode: 0750
    owner: root
    group: root
    state: directory

- name: Shell Detector | install cron script
  template:
    src: shelldetector.cron.j2
    dest: /usr/local/bin/shelldetector_cron.sh
    owner: root
    group: root
    mode: 0750

- name: Shell Detector | creates daily cronjob
  cron:
    name: "Launch Shell Detector audit"
    hour: "{{ shelldetector_cron_hour }}"
    minute: "{{ shelldetector_cron_minute }}"
    weekday: "*"
    cron_file: "shelldetector"
    user: "root"
    job: "/usr/local/bin/shelldetector_cron.sh 2>&1 | logger"
